version: v1
api_prefix: /api/${version}
application_name: apiGateway
server_port: 8078

server:
  error:
    whitelabel:
      enabled: true
  port: ${server_port}
spring:
  application:
    name: ${application_name}
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: products
          uri: lb://PRODUCTS
          predicates:
            - Path=/${api_prefix}/products/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true