IF DB_ID('$(MSSQL_DB)') IS NULL
BEGIN
  CREATE DATABASE $(MSSQL_DB);

  SELECT 'The Database $(MSSQL_DB) has been Created';
END;
ELSE SELECT 'The Database $(MSSQL_DB) already exists';


ALTER DATABASE $(MSSQL_DB) SET AUTO_CLOSE OFF;


--USE $(MSSQL_DB);
--GO

--CREATE LOGIN $(MSSQL_USER) WITH PASSWORD='$(MSSQL_PASSWORD)';
--GO

--CREATE USER $(MSSQL_USER) FOR LOGIN $(MSSQL_USER);
--GO

--ALTER SERVER ROLE sysadmin ADD MEMBER [$(MSSQL_USER)];
--GO