version: v1
api_prefix: /api/${version}
application_name: eureka-server
server_port: 8761

spring:
  application:
    name: ${application_name}
  zipkin:
    base-url: http://localhost:9411

server:
  error:
    whitelabel:
      enabled: true
  port: ${server_port}

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false