version: v1
api_prefix: /api/${version}
application_name: clients
server_port: 8073


server:
  error:
    whitelabel:
      enabled: true
  port: ${server_port}
spring:
  application:
    name: ${application_name}
 
clients:
  errors:
    url: http://localhost:8072